rm -r ./raw/*
python S1Processor.py S1Processor_april.cfg
rm -r ./raw/*
python S1Processor.py S1Processor_may.cfg
rm -r ./raw/*
python S1Processor.py S1Processor_june.cfg
rm -r ./raw/*
python S1Processor.py S1Processor_july.cfg
rm -r ./raw/*
python S1Processor.py S1Processor_august.cfg
rm -r ./raw/*
python S1Processor.py S1Processor_september.cfg
rm -r ./raw/*
python S1Processor.py S1Processor_october.cfg
rm -r ./raw/*
python S1Processor.py S1Processor_november.cfg
rm -r ./raw/*
python S1Processor.py S1Processor_december.cfg
rm -r ./raw/*
